# Главный тип
type Client {
  id: int
  name: String
  documents: [Document]  # Информация о документах клиента
  relatives: [Relative]  # Информация о родственниках клиента
}

type Document {
  id: int
  type: String
  number: String
  issueDate: Date
  expiryDate: Date
}

type Relative {
  id: int
  name: String
  relationType: String
}

# Тип запроса, который извлекает одного клиента
type Query {
	getClient(id: String!): Client
	getClientDocuments(id: String!): [Document]
    getClientRelatives(id: String!): [Relative]
}

